# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 13:56
from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.auth.models import User
import django.db.models.deletion


def create_superuser(apps, schema_editor):
    u = User(username='admin')
    u.set_password('csv123456')
    u.is_superuser = True
    u.is_staff = True
    u.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0430',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='ParserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country', verbose_name='\u041f\u0430\u0440\u0430\u043c\u0435\u0442\u0440')),
            ],
            options={
                'verbose_name': '\u0414\u0430\u043d\u043d\u044b\u0435',
                'verbose_name_plural': '\u0414\u0430\u043d\u043d\u044b\u0435',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b',
            },
        ),
        migrations.AddField(
            model_name='parserdata',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Region', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430'),
        ),
        migrations.RunPython(create_superuser)
    ]
